[package]
name = "bevy_sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_quadtree = {version = "0.15.2"}
leafwing-input-manager = "0.16.0"
bevy_ecs_tiled = {version="0.6", features=["physics"]}
bevy_ecs_tilemap = "0.15"

[profile.dev.package."*"]
opt-level = 3

