[package]
name = "bevy_sandbox"
version = "0.1.1"
edition = "2024"

[dependencies]
bevy = "0.16"
bevy_quadtree = {version = "0.16"}
leafwing-input-manager = "0.17.0"
bevy_ecs_tiled = {version="0.7", features=["physics"]}
bevy_ecs_tilemap = "0.16"

[profile.dev.package."*"]
opt-level = 3

