[package]
name = "bevy_sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_quadtree = {version = "0.15.2", features = ["sprite"]}
leafwing-input-manager = "0.16.0"

[profile.dev.package."*"]
opt-level = 3

